

--Crear base de datos empresa
CREATE DATABASE empresa;

--Usar base de datos empresa;
USE empresa;

--Crear tabla departamento
CREATE TABLE departamento( cod_depto INTEGER PRIMARY KEY, nombre VARCHAR(70) NOT NULL, localidad VARCHAR(70) NOT NULL); 

--Crear tabla empleados
CREATE TABLE empleados(cod_emp INTEGER PRIMARY KEY, nombre VARCHAR(70), apellido1 VARCHAR(70), apellido2 VARCHAR(70) , contratado DATE, departamento INTEGER,responsable INTEGER,trabajo VARCHAR(70), salario INTEGER);

--Añade clave foranea
ALTER TABLE empleados ADD FOREIGN KEY (departamento) REFERENCES departamento(cod_depto);

--Añadimos los datos a la tabla departamentos
-- $scp departamento.sql juanma@192.168.23.93:~
-- $mysql -u admin -p empresa < departamento.sql

--o

insert into departamento (cod_depto, nombre, localidad) values (1, 'VENTAS', 'CORDOBA');
insert into departamento (cod_depto, nombre, localidad) values (2, 'CONTABILIDAD', 'SEVILLA');
insert into departamento (cod_depto, nombre, localidad) values (3, 'VENTAS', 'JAEN');
insert into departamento (cod_depto, nombre, localidad) values (4, 'I+D', 'CORDOBA');
insert into departamento (cod_depto, nombre, localidad) values (5, 'OPERACIONES', 'SEVILLA');
insert into departamento (cod_depto, nombre, localidad) values (6, 'VENTAS', 'JAEN');
insert into departamento (cod_depto, nombre, localidad) values (7, 'VENTAS', 'CORDOBA');
insert into departamento (cod_depto, nombre, localidad) values (8, 'I+D', 'CORDOBA');
insert into departamento (cod_depto, nombre, localidad) values (9, 'I+D', 'SEVILLA');
insert into departamento (cod_depto, nombre, localidad) values (10, 'OPERACIONES', 'JAEN');

--Actualizamos algunos datos para evitar repticiones

UPDATE departamento SET nombre='OPERACIONES' WHERE cod_depto='4';
UPDATE departamento SET localidad='SEVILLA' WHERE cod_depto='1';

--Añadimos los datos a la tabla empleados
-- $scp empleados.sql juanma@192.168.23.93:~
-- $mysql -u admin -p empresa < empleados.sql

--o

insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (1, 'Mable', 'Willets', 'Machent', '2016-08-15', 6, 'VENTAS', 3335);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (2, 'Roda', 'Cossins', 'Mebius', '2013-12-06', 2, 'VENTAS', 2109);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (3, 'Perry', 'Kimbury', 'Stutely', '2016-08-13', 8, 'VENTAS', 4357);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (4, 'Granny', 'Ambroisin', 'Alleburton', '2003-01-01', 7, 'VENTAS', 1646);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (5, 'Juliet', 'Brodeau', 'Peacocke', '2016-10-18', 6, 'VENTAS', 2512);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (6, 'Laural', 'Summers', 'Largan', '2016-02-26', 5, 'VENTAS', 3552);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (7, 'Marrissa', 'Ricciardi', 'Ricart', '2011-06-30', 7, 'ANALISTA', 3631);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (8, 'Filippa', 'Malmar', 'Mulmuray', '2016-04-07', 9, 'ADMINISTRACIÓN', 2982);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (9, 'Lindsey', 'Summerson', 'Goldspink', '2015-03-27', 5, 'ANALISTA', 1226);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (10, 'Carlina', 'Muckian', 'Celes', '2018-11-19', 9, 'VENTAS', 1152);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (11, 'Rachele', 'Hansmann', 'Hulland', '2019-01-29', 3, 'ANALISTA', 2565);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (12, 'Rancell', 'Novic', 'Rasell', '2007-07-11', 9, 'ANALISTA', 4800);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (13, 'Bar', 'Bannard', 'Greatbanks', '2018-06-06', 1, 'ADMINISTRACIÓN', 3737);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (14, 'Konstanze', 'Daltrey', 'Martinolli', '2019-08-02', 5, 'ANALISTA', 3471);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (15, 'Jillane', 'Deners', 'Flucker', '2003-11-16', 1, 'VENTAS', 2319);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (16, 'Ashli', 'Gibson', 'Ruhben', '2009-12-17', 8, 'ADMINISTRACIÓN', 1241);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (17, 'Dacey', 'Dungate', 'Cadwallader', '2015-02-24', 10, 'ADMINISTRACIÓN', 3655);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (18, 'Alika', 'Hubbins', 'Smalecombe', '2009-03-27', 3, 'ADMINISTRACIÓN', 3926);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (19, 'Karel', 'Simondson', 'Birrel', '2016-05-02', 3, 'ANALISTA', 3858);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (20, 'Easter', 'Fricke', 'Kibbel', '2015-06-06', 2, 'ADMINISTRACIÓN', 1578);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (21, 'Christean', 'Jeffery', 'Grandisson', '2017-12-03', 3, 'ANALISTA', 3243);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (22, 'Caren', 'Colbron', 'Ridolfo', '2018-06-23', 2, 'ANALISTA', 3944);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (23, 'Lowe', 'Carcass', 'Uppett', '2018-03-29', 7, 'ADMINISTRACIÓN', 3395);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (24, 'Jeannette', 'Lidgerton', 'Livingstone', '2019-02-19', 1, 'ANALISTA', 999);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (25, 'Ginelle', 'Wloch', 'Callacher', '2006-12-25', 5, 'ADMINISTRACIÓN', 2199);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (26, 'Teddie', 'Salzberger', 'Grigoli', '2013-12-14', 6, 'ANALISTA', 4974);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (27, 'Morgen', 'Seally', 'Meeny', '2017-06-27', 4, 'ANALISTA', 2606);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (28, 'Jacquelynn', 'McMains', 'Osmint', '2012-09-19', 5, 'ADMINISTRACIÓN', 2787);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (29, 'Dacie', 'Bulmer', 'Kas', '2010-09-15', 7, 'ANALISTA', 3189);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (30, 'Zack', 'State', 'Hasker', '2018-12-11', 3, 'ANALISTA', 4678);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (31, 'Elias', 'Samme', 'Scarfe', '2003-07-13', 4, 'ADMINISTRACIÓN', 2791);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (32, 'Torre', 'Thynne', 'Emblin', '2004-10-24', 1, 'ADMINISTRACIÓN', 3201);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (33, 'Sigfrid', 'Duffer', 'Andraud', '2014-03-25', 3, 'ADMINISTRACIÓN', 1170);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (34, 'Dru', 'Kencott', 'Zimmer', '2003-11-21', 3, 'ADMINISTRACIÓN', 2735);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (35, 'Ofella', 'Jarrelt', 'Markel', '2008-02-13', 6, 'VENTAS', 3277);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (36, 'Burk', 'Norwood', 'Shirrell', '2014-04-18', 10, 'VENTAS', 3688);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (37, 'Thatch', 'Swinburne', 'Bartrap', '2006-09-13', 5, 'ADMINISTRACIÓN', 1761);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (38, 'Chery', 'Crosen', 'Gorhardt', '2010-03-06', 5, 'ANALISTA', 4273);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (39, 'Kizzie', 'Watchorn', 'Jeannet', '2005-09-28', 3, 'ANALISTA', 2551);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (40, 'Garrick', 'Agget', 'Smorthit', '2005-02-19', 4, 'ANALISTA', 3957);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (41, 'Lorita', 'Saunier', 'Ollington', '2012-04-11', 1, 'ADMINISTRACIÓN', 3860);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (42, 'Karla', 'Ryson', 'Hadingham', '2015-12-25', 3, 'ANALISTA', 4989);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (43, 'Nisse', 'Henricsson', 'Ellcome', '2011-06-04', 2, 'ANALISTA', 3504);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (44, 'Aurelea', 'McGaugey', 'Cowill', '2008-12-22', 2, 'ANALISTA', 4072);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (45, 'Allene', 'McGuiney', 'Ethelston', '2019-06-21', 8, 'ANALISTA', 1475);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (46, 'Giacopo', 'Moodie', 'McVaugh', '2010-02-05', 4, 'ANALISTA', 2203);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (47, 'Eduino', 'Ludye', 'Pellatt', '2018-09-03', 8, 'ADMINISTRACIÓN', 3252);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (48, 'Carolee', 'Gilbey', 'Colrein', '2012-09-05', 9, 'ANALISTA', 4706);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (49, 'Sargent', 'Greenham', 'Stebbings', '2013-09-19', 7, 'ADMINISTRACIÓN', 4683);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (50, 'Waiter', 'Ivons', 'Urian', '2004-09-20', 7, 'VENTAS', 4377);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (51, 'Irv', 'Duxbarry', 'Brusin', '2017-09-28', 7, 'ANALISTA', 4738);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (52, 'Damaris', 'Antoniottii', 'Shelvey', '2016-06-14', 10, 'VENTAS', 4728);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (53, 'Roseann', 'Skillen', 'Wigelsworth', '2016-11-24', 2, 'VENTAS', 4492);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (54, 'Orville', 'D''Aguanno', 'Albrooke', '2013-06-14', 10, 'VENTAS', 2605);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (55, 'Theresa', 'Ingry', 'Pearlman', '2009-07-29', 1, 'ADMINISTRACIÓN', 1128);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (56, 'Rickard', 'Gobert', 'Tipperton', '2014-02-15', 9, 'ANALISTA', 1792);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (57, 'Yvor', 'Theobald', 'Edbrooke', '2019-07-28', 5, 'VENTAS', 2252);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (58, 'Sidonia', 'Lockier', 'Ferrini', '2016-04-22', 1, 'ANALISTA', 1330);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (59, 'Bartie', 'Hobbing', 'Hedden', '2005-07-08', 7, 'VENTAS', 2406);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (60, 'Vicky', 'Boylan', 'Burkwood', '2011-03-23', 9, 'VENTAS', 1078);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (61, 'Dougie', 'Cathro', 'Hunnisett', '2010-10-16', 7, 'ADMINISTRACIÓN', 4226);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (62, 'Alberta', 'Rickards', 'Gaskall', '2017-08-15', 1, 'ADMINISTRACIÓN', 3598);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (63, 'Shayne', 'Killeen', 'Taggert', '2017-11-04', 3, 'ANALISTA', 2036);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (64, 'Courtenay', 'Chazerand', 'Rishman', '2005-11-11', 7, 'ANALISTA', 4495);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (65, 'Bethany', 'Buzza', 'Nickolls', '2009-08-23', 7, 'ANALISTA', 2841);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (66, 'Queenie', 'Kilalea', 'Dilland', '2014-11-06', 4, 'ANALISTA', 3173);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (67, 'Bruno', 'Surplice', 'Biddleston', '2007-09-27', 7, 'ADMINISTRACIÓN', 2271);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (68, 'Brandea', 'Szapiro', 'Petrushkevich', '2012-05-04', 10, 'ADMINISTRACIÓN', 2526);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (69, 'Skipton', 'Bromehed', 'Madre', '2007-06-06', 7, 'ADMINISTRACIÓN', 3770);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (70, 'Charity', 'Managh', 'Budding', '2003-08-23', 7, 'ADMINISTRACIÓN', 2143);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (71, 'Wynne', 'Artois', 'Weed', '2009-07-07', 2, 'ADMINISTRACIÓN', 4153);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (72, 'Izzy', 'Aldcorne', 'Toombes', '2011-02-11', 3, 'VENTAS', 2452);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (73, 'Lindon', 'Grindrod', 'Crass', '2013-01-27', 7, 'ADMINISTRACIÓN', 3388);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (74, 'Zitella', 'Heigl', 'Mirfield', '2005-08-28', 3, 'VENTAS', 3912);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (75, 'Cornie', 'McGilbon', 'Kidstone', '2017-04-02', 8, 'ADMINISTRACIÓN', 4600);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (76, 'Murial', 'Devereu', 'Mattheus', '2018-09-11', 1, 'ADMINISTRACIÓN', 1632);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (77, 'Nariko', 'Roswarne', 'McWilliam', '2007-09-07', 8, 'ANALISTA', 3990);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (78, 'Merrick', 'Barnbrook', 'Althorp', '2012-02-07', 7, 'ANALISTA', 1924);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (79, 'Cassandre', 'Baudi', 'Gilbey', '2003-10-13', 1, 'ADMINISTRACIÓN', 4306);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (80, 'Alexandre', 'Fierman', 'Phillp', '2015-03-20', 1, 'ADMINISTRACIÓN', 1842);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (81, 'Emanuel', 'Labroue', 'Gorgler', '2005-09-02', 10, 'ADMINISTRACIÓN', 3996);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (82, 'Conney', 'Rodolfi', 'Pomroy', '2006-08-13', 8, 'ANALISTA', 2966);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (83, 'Ferdinand', 'Korb', 'Calwell', '2018-05-15', 4, 'ANALISTA', 3853);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (84, 'Jefferson', 'Bramhill', 'Twittey', '2014-08-03', 1, 'ANALISTA', 2694);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (85, 'Burgess', 'Pechold', 'Scullard', '2013-04-27', 9, 'ADMINISTRACIÓN', 3076);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (86, 'Orran', 'Ruffy', 'Gadson', '2013-11-10', 10, 'ANALISTA', 3312);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (87, 'Gabriel', 'Jocic', 'Sauvain', '2005-01-28', 4, 'VENTAS', 3452);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (88, 'Justinn', 'McCrohon', 'Tudor', '2008-08-07', 8, 'VENTAS', 4659);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (89, 'Fanny', 'Girtin', 'Lanon', '2017-05-12', 3, 'VENTAS', 4449);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (90, 'Jo ann', 'Dewsbury', 'Bille', '2003-12-25', 1, 'VENTAS', 2367);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (91, 'Gretta', 'Halahan', 'Hutchence', '2012-02-07', 1, 'ANALISTA', 2624);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (92, 'Zaneta', 'Nussen', 'Hitter', '2006-06-02', 9, 'VENTAS', 3132);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (93, 'Jolie', 'Giorgetti', 'Garman', '2012-12-26', 10, 'ADMINISTRACIÓN', 3028);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (94, 'Barton', 'Thickins', 'Clifton', '2017-12-14', 8, 'ADMINISTRACIÓN', 3851);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (95, 'Nananne', 'Yoell', 'Cremins', '2019-05-31', 1, 'VENTAS', 1346);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (96, 'Conny', 'Wadeson', 'Fermor', '2015-03-23', 9, 'ANALISTA', 2477);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (97, 'Delmore', 'Bernardo', 'Serraillier', '2013-10-01', 9, 'ADMINISTRACIÓN', 1206);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (98, 'Alexia', 'Lesek', 'Nial', '2009-05-01', 6, 'ADMINISTRACIÓN', 1282);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (99, 'Marie', 'Luberto', 'Truss', '2007-02-24', 1, 'VENTAS', 2498);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (100, 'Nannette', 'Worsnap', 'Romera', '2006-02-10', 5, 'ADMINISTRACIÓN', 3047);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (101, 'Ebonee', 'Winch', 'Tolworthie', '2006-06-24', 8, 'VENTAS', 3438);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (102, 'Clarence', 'Adamoli', 'de Aguirre', '2003-11-13', 6, 'ADMINISTRACIÓN', 1756);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (103, 'Guglielma', 'Willimont', 'Woosnam', '2015-11-27', 6, 'ADMINISTRACIÓN', 2038);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (104, 'Elita', 'Pallesen', 'Lockner', '2005-07-22', 4, 'ADMINISTRACIÓN', 2768);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (105, 'Norene', 'Gillyett', 'Harlick', '2015-11-14', 6, 'ADMINISTRACIÓN', 3319);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (106, 'Bartholomew', 'Coghlan', 'Wanless', '2015-02-24', 8, 'ADMINISTRACIÓN', 1174);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (107, 'Clareta', 'Spaunton', 'Pierri', '2017-03-09', 7, 'ADMINISTRACIÓN', 2728);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (108, 'Pepita', 'Calken', 'Doorly', '2018-11-16', 3, 'ANALISTA', 1596);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (109, 'Celestine', 'Lissandri', 'Evenden', '2003-10-03', 4, 'VENTAS', 4158);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (110, 'Carita', 'Vlasov', 'Sherar', '2007-12-05', 5, 'ANALISTA', 1766);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (111, 'Piotr', 'Sotheby', 'Haycox', '2015-06-27', 5, 'ANALISTA', 2623);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (112, 'Vicky', 'McAuley', 'Ambrogioli', '2015-09-06', 10, 'ANALISTA', 1273);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (113, 'Karia', 'Sayburn', 'Dunkerly', '2003-05-13', 6, 'ADMINISTRACIÓN', 960);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (114, 'Madlin', 'Muldoon', 'Gerram', '2006-11-14', 3, 'ANALISTA', 2031);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (115, 'Adolphe', 'Dayes', 'Humbles', '2016-03-26', 8, 'ANALISTA', 1613);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (116, 'Ilise', 'Befroy', 'Richichi', '2012-05-26', 7, 'ANALISTA', 4005);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (117, 'Giselle', 'Hellsdon', 'Markushkin', '2008-11-20', 4, 'ADMINISTRACIÓN', 3470);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (118, 'Reinhold', 'Landreth', 'Pettiford', '2007-06-13', 9, 'ANALISTA', 3760);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (119, 'Hieronymus', 'Sier', 'Kunrad', '2010-08-08', 2, 'VENTAS', 1966);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (120, 'Nicky', 'Conant', 'Charrett', '2010-07-21', 1, 'VENTAS', 3708);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (121, 'Claiborne', 'Casillis', 'Emilien', '2003-09-07', 2, 'ADMINISTRACIÓN', 2863);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (122, 'Alice', 'Naish', 'Oultram', '2007-03-19', 3, 'VENTAS', 2818);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (123, 'Renate', 'Thatcham', 'Menault', '2017-06-25', 6, 'VENTAS', 4950);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (124, 'Nelle', 'Farnill', 'Clemmitt', '2007-05-04', 8, 'VENTAS', 1676);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (125, 'Billie', 'Grangier', 'Pimblott', '2005-06-01', 8, 'ANALISTA', 4702);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (126, 'Flo', 'Lantaph', 'Malcolmson', '2008-09-23', 10, 'ADMINISTRACIÓN', 3901);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (127, 'Anna', 'Kettlestringes', 'Rennix', '2014-09-25', 3, 'ADMINISTRACIÓN', 4563);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (128, 'Pearline', 'Saffin', 'Walling', '2008-11-05', 4, 'ADMINISTRACIÓN', 2261);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (129, 'Bary', 'Pechet', 'Cripwell', '2005-09-07', 7, 'ANALISTA', 1316);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (130, 'Jenda', 'Metzel', 'Standering', '2014-11-02', 10, 'ANALISTA', 3290);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (131, 'Spike', 'Grebert', 'Trevallion', '2010-05-29', 9, 'ANALISTA', 4193);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (132, 'Parrnell', 'Norquay', 'Whiston', '2007-09-04', 5, 'VENTAS', 3453);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (133, 'Greta', 'Colliver', 'Loughney', '2010-12-17', 9, 'ANALISTA', 3171);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (134, 'Ernestus', 'Megarrell', 'Minto', '2019-01-24', 1, 'ANALISTA', 2190);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (135, 'Miles', 'Rubertelli', 'McSperron', '2005-05-30', 10, 'ADMINISTRACIÓN', 1806);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (136, 'Nappie', 'Itzhayek', 'Kermott', '2012-08-09', 5, 'VENTAS', 4220);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (137, 'Melosa', 'Bigglestone', 'Reimers', '2006-06-28', 6, 'ANALISTA', 4689);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (138, 'Enrique', 'Hedlestone', 'Oseman', '2012-03-14', 3, 'ADMINISTRACIÓN', 1114);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (139, 'Ailey', 'Pawfoot', 'Mayoh', '2011-06-13', 6, 'VENTAS', 4459);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (140, 'Merrilee', 'Southall', 'Pyecroft', '2007-12-28', 5, 'ADMINISTRACIÓN', 3343);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (141, 'Philly', 'Mayhead', 'Steeples', '2010-10-19', 5, 'ANALISTA', 1165);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (142, 'Regine', 'Danniel', 'Maddigan', '2014-02-23', 4, 'VENTAS', 2195);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (143, 'Morly', 'Cardwell', 'Raleston', '2008-07-21', 9, 'ANALISTA', 2665);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (144, 'Morgen', 'Bottom', 'Spiers', '2006-11-29', 6, 'VENTAS', 1259);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (145, 'Layton', 'Di Claudio', 'Lorne', '2016-10-10', 9, 'ADMINISTRACIÓN', 4559);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (146, 'Clerkclaude', 'Wimp', 'Emmott', '2012-11-12', 6, 'VENTAS', 1779);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (147, 'Paton', 'Gashion', 'Kelbie', '2012-08-24', 4, 'ANALISTA', 1455);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (148, 'Gothart', 'Sailes', 'Mapston', '2018-04-14', 9, 'ANALISTA', 1837);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (149, 'Hillie', 'Wilhelmy', 'Roundtree', '2004-01-03', 3, 'ADMINISTRACIÓN', 1456);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (150, 'Candi', 'Woodfin', 'Bottby', '2007-05-15', 7, 'ANALISTA', 4710);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (151, 'Cobby', 'Varty', 'Branchet', '2016-12-02', 5, 'ANALISTA', 2434);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (152, 'Urbanus', 'Scally', 'Di Franceschi', '2017-04-06', 4, 'ADMINISTRACIÓN', 2802);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (153, 'Isadora', 'Lavallie', 'Steptow', '2009-12-29', 3, 'ANALISTA', 3176);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (154, 'Ninette', 'Whittock', 'Ferrieres', '2016-05-11', 4, 'VENTAS', 2076);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (155, 'Neville', 'Merck', 'Lethbury', '2008-03-17', 7, 'VENTAS', 3991);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (156, 'Colver', 'Eccott', 'Fawks', '2008-09-15', 2, 'ADMINISTRACIÓN', 3508);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (157, 'Dallon', 'Cromblehome', 'Bleackly', '2006-06-11', 9, 'VENTAS', 4700);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (158, 'Lorinda', 'Dybald', 'Jest', '2010-03-23', 7, 'ANALISTA', 4581);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (159, 'Lisbeth', 'O''Flaverty', 'Masarrat', '2011-09-04', 6, 'ANALISTA', 2986);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (160, 'Shelly', 'Ferraretto', 'Birch', '2003-05-09', 3, 'ADMINISTRACIÓN', 3633);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (161, 'Alica', 'Oswick', 'Jouanet', '2011-12-31', 10, 'VENTAS', 1818);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (162, 'Caria', 'Bernocchi', 'Astall', '2004-09-09', 8, 'VENTAS', 1969);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (163, 'Roxine', 'Corss', 'Critten', '2005-10-29', 3, 'ANALISTA', 1281);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (164, 'Boycey', 'Wetherby', 'Mouatt', '2007-03-25', 4, 'ANALISTA', 1853);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (165, 'Brad', 'Korneluk', 'Thorns', '2011-09-16', 9, 'VENTAS', 3646);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (166, 'Renae', 'Medland', 'Portugal', '2005-12-01', 3, 'VENTAS', 3428);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (167, 'Uriah', 'Cauldwell', 'Rides', '2017-03-28', 9, 'ADMINISTRACIÓN', 3214);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (168, 'Mort', 'Oswald', 'Bedborough', '2010-04-10', 1, 'ANALISTA', 2250);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (169, 'Mariquilla', 'Jaffa', 'Knoble', '2004-10-01', 9, 'VENTAS', 902);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (170, 'Sophronia', 'Haycraft', 'Elvy', '2013-06-11', 1, 'ADMINISTRACIÓN', 988);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (171, 'Thorin', 'Laughton', 'Whitehorn', '2012-12-07', 3, 'ADMINISTRACIÓN', 4052);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (172, 'Darrell', 'Dowding', 'Rylett', '2008-06-30', 9, 'ANALISTA', 4628);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (173, 'Bennie', 'Fetherby', 'Nutley', '2012-10-11', 2, 'ANALISTA', 1424);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (174, 'Dannel', 'Attfield', 'Gazey', '2005-01-31', 4, 'ADMINISTRACIÓN', 3174);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (175, 'Erny', 'Whild', 'Schwandner', '2018-11-19', 5, 'ADMINISTRACIÓN', 2723);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (176, 'Judy', 'Kervin', 'Choake', '2005-10-07', 6, 'ADMINISTRACIÓN', 4473);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (177, 'Corty', 'Valek', 'Faint', '2007-09-13', 8, 'VENTAS', 1554);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (178, 'Myrlene', 'Gibbett', 'Wandrey', '2010-06-09', 3, 'ADMINISTRACIÓN', 2439);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (179, 'Emery', 'Laydon', 'Lindop', '2014-08-12', 5, 'ADMINISTRACIÓN', 2428);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (180, 'Eimile', 'Rzehorz', 'Aguilar', '2018-08-24', 7, 'VENTAS', 2840);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (181, 'Merwin', 'Readmire', 'Gadie', '2006-03-23', 8, 'VENTAS', 3443);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (182, 'Teodora', 'Simmen', 'Rhelton', '2017-10-12', 4, 'ANALISTA', 4624);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (183, 'Duff', 'Mintoff', 'Powis', '2003-03-07', 9, 'ADMINISTRACIÓN', 3581);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (184, 'Freida', 'Caser', 'Farquharson', '2007-08-16', 10, 'VENTAS', 1909);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (185, 'Garnette', 'Maltby', 'Randlesome', '2014-08-07', 4, 'ANALISTA', 2084);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (186, 'Hyacinthia', 'Pridgeon', 'Mabon', '2015-08-21', 7, 'VENTAS', 1353);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (187, 'Jori', 'Semor', 'Forrest', '2009-01-06', 6, 'ANALISTA', 3905);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (188, 'Cathrine', 'Grinvalds', 'Saltman', '2012-01-13', 7, 'VENTAS', 4158);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (189, 'Ailis', 'Marskell', 'Garric', '2004-01-26', 9, 'ANALISTA', 4826);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (190, 'Jana', 'Critzen', 'Wyllie', '2007-05-19', 7, 'ANALISTA', 1886);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (191, 'Jessamyn', 'Georgi', 'Meddings', '2005-07-06', 5, 'VENTAS', 4857);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (192, 'Alaster', 'Swires', 'St Ange', '2009-05-06', 8, 'VENTAS', 3932);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (193, 'Roth', 'Rapa', 'Passler', '2014-06-19', 6, 'ANALISTA', 3205);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (194, 'Miguel', 'Garrod', 'Starbuck', '2017-09-16', 8, 'ADMINISTRACIÓN', 3739);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (195, 'Shelagh', 'D''Alesco', 'Bottelstone', '2004-01-04', 4, 'ADMINISTRACIÓN', 3997);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (196, 'Karel', 'Mathevon', 'Spleving', '2019-05-24', 2, 'ANALISTA', 1885);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (197, 'Jabez', 'McIan', 'Ferreres', '2004-06-22', 7, 'VENTAS', 1871);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (198, 'Merle', 'Weddeburn', 'Lemanu', '2014-03-04', 10, 'ANALISTA', 1523);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (199, 'Dorthy', 'Culley', 'McGready', '2012-04-30', 6, 'VENTAS', 3194);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (200, 'Kirsti', 'Boast', 'Ashworth', '2011-07-22', 4, 'ADMINISTRACIÓN', 3234);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (201, 'Rollo', 'Oakton', 'Bernakiewicz', '2017-03-16', 8, 'VENTAS', 3828);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (202, 'Alfredo', 'Gerber', 'Warricker', '2016-05-20', 5, 'ADMINISTRACIÓN', 2953);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (203, 'Felita', 'Heindle', 'Taillant', '2008-07-21', 1, 'ADMINISTRACIÓN', 3096);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (204, 'Kaiser', 'Blethyn', 'Marchiso', '2011-01-12', 9, 'VENTAS', 4918);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (205, 'Cristy', 'Reignolds', 'Summerside', '2015-06-27', 3, 'ADMINISTRACIÓN', 3058);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (206, 'Pryce', 'Sandle', 'Levicount', '2016-01-19', 4, 'ANALISTA', 2985);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (207, 'Margalit', 'Royste', 'Caffin', '2010-06-11', 3, 'VENTAS', 3214);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (208, 'Rosmunda', 'Sherratt', 'Dootson', '2017-03-31', 7, 'ANALISTA', 1327);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (209, 'Neila', 'Haliday', 'Corss', '2017-12-07', 5, 'VENTAS', 4561);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (210, 'Victor', 'Dumphrey', 'Seal', '2012-03-30', 10, 'VENTAS', 3052);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (211, 'Husain', 'Finby', 'Measen', '2003-05-28', 3, 'ADMINISTRACIÓN', 4675);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (212, 'Carin', 'Marshal', 'Braime', '2006-05-20', 5, 'ADMINISTRACIÓN', 4750);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (213, 'Iggy', 'Bunyard', 'Bernon', '2012-10-09', 8, 'ANALISTA', 4338);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (214, 'Hilary', 'Fortnum', 'Rennenbach', '2008-12-01', 8, 'ADMINISTRACIÓN', 3864);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (215, 'Carlyn', 'Domotor', 'Upcott', '2007-06-16', 9, 'ANALISTA', 1484);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (216, 'Melody', 'Byway', 'Calder', '2015-04-16', 6, 'ANALISTA', 3693);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (217, 'Kristoforo', 'Sottell', 'Hebborne', '2013-11-22', 2, 'VENTAS', 3467);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (218, 'Laurella', 'Kettridge', 'Lachaize', '2005-02-23', 10, 'ADMINISTRACIÓN', 1107);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (219, 'Carrol', 'Dady', 'Rouchy', '2015-11-25', 10, 'ANALISTA', 1942);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (220, 'Dore', 'Girardi', 'D''Aeth', '2012-01-08', 5, 'ADMINISTRACIÓN', 3693);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (221, 'Brandon', 'Tiner', 'Hutable', '2013-09-08', 2, 'ADMINISTRACIÓN', 3525);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (222, 'Eulalie', 'Tolomei', 'Assaf', '2003-12-03', 5, 'VENTAS', 4000);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (223, 'Omar', 'Imms', 'Eicheler', '2004-11-19', 10, 'VENTAS', 4480);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (224, 'Donelle', 'Riby', 'Cockney', '2015-08-24', 2, 'ADMINISTRACIÓN', 1939);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (225, 'Bryna', 'Salthouse', 'Rodgman', '2007-10-21', 8, 'ANALISTA', 3285);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (226, 'Arlen', 'Killelay', 'Ilyunin', '2016-03-15', 7, 'ANALISTA', 1672);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (227, 'Josie', 'Govini', 'Cathrae', '2005-04-26', 3, 'ANALISTA', 3097);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (228, 'Dodi', 'Sego', 'Tilt', '2018-05-30', 3, 'VENTAS', 2858);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (229, 'Kevin', 'Gabrieli', 'Hanster', '2005-01-10', 6, 'ADMINISTRACIÓN', 1026);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (230, 'Nealy', 'Sowrey', 'Tilio', '2006-08-22', 1, 'VENTAS', 3225);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (231, 'Prisca', 'Forrest', 'Bowling', '2011-01-06', 1, 'VENTAS', 1850);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (232, 'Claus', 'Hefford', 'McCombe', '2016-03-31', 1, 'ANALISTA', 1988);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (233, 'Malvin', 'Simmill', 'Payle', '2016-06-22', 6, 'ANALISTA', 1933);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (234, 'Helsa', 'Travers', 'Tesauro', '2012-03-19', 3, 'VENTAS', 1016);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (235, 'Sunshine', 'Vittore', 'Don', '2010-07-04', 7, 'ANALISTA', 2317);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (236, 'Ettie', 'Pendrigh', 'Jindacek', '2009-05-31', 7, 'VENTAS', 1983);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (237, 'Berri', 'Kensett', 'Savory', '2012-04-12', 8, 'ADMINISTRACIÓN', 3843);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (238, 'Maybelle', 'Fayne', 'Elstone', '2013-01-20', 5, 'ADMINISTRACIÓN', 1330);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (239, 'Merilee', 'Dahlborg', 'Yanne', '2011-05-01', 8, 'ADMINISTRACIÓN', 1723);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (240, 'Pearl', 'Fassan', 'Carrigan', '2006-04-20', 8, 'ADMINISTRACIÓN', 2565);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (241, 'Riordan', 'Millimoe', 'Harron', '2011-12-08', 9, 'ANALISTA', 2091);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (242, 'Barbette', 'Duro', 'Rowler', '2012-10-20', 4, 'VENTAS', 1952);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (243, 'Tomkin', 'Moxley', 'Rabidge', '2010-10-02', 8, 'VENTAS', 2770);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (244, 'Brad', 'Brimble', 'Lowsely', '2009-12-16', 10, 'ANALISTA', 4430);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (245, 'Adelle', 'Breston', 'Simpkin', '2018-07-15', 2, 'VENTAS', 1677);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (246, 'Esme', 'McAless', 'Tretter', '2014-10-22', 1, 'ANALISTA', 1095);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (247, 'Jacky', 'Malecky', 'Jacobovitch', '2015-08-30', 5, 'ADMINISTRACIÓN', 4326);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (248, 'Wanids', 'Greenough', 'Kubes', '2011-08-04', 10, 'ADMINISTRACIÓN', 3261);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (249, 'Cati', 'Nutton', 'Greenrodd', '2011-08-22', 1, 'VENTAS', 4356);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (250, 'Katrinka', 'Goburn', 'Jacombs', '2009-06-23', 3, 'VENTAS', 2622);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (251, 'Kayle', 'Itzkovwich', 'Hamlyn', '2016-06-15', 5, 'ANALISTA', 1019);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (252, 'Marty', 'Somerton', 'Moisey', '2015-04-08', 10, 'ADMINISTRACIÓN', 4109);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (253, 'Ariel', 'Windybank', 'Millthorpe', '2004-01-18', 10, 'VENTAS', 3723);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (254, 'Linea', 'Speenden', 'Zucker', '2008-11-07', 7, 'ADMINISTRACIÓN', 1062);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (255, 'Arnold', 'Raynham', 'Tunnacliffe', '2011-09-26', 5, 'ANALISTA', 1021);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (256, 'Odette', 'Clench', 'Berzin', '2006-10-31', 7, 'ANALISTA', 3497);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (257, 'Jacquelyn', 'Oaten', 'Tolomio', '2007-10-31', 5, 'VENTAS', 3530);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (258, 'Orlando', 'Waistall', 'Hein', '2004-11-03', 1, 'VENTAS', 1810);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (259, 'Ollie', 'Maling', 'Hambridge', '2005-12-20', 6, 'VENTAS', 3761);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (260, 'Maryanne', 'Tizard', 'Foreman', '2019-04-29', 5, 'VENTAS', 1998);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (261, 'Natividad', 'Knok', 'Roan', '2006-09-08', 1, 'ANALISTA', 2575);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (262, 'Alix', 'Salmons', 'Bartlomieczak', '2019-07-17', 8, 'VENTAS', 3523);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (263, 'Welby', 'Sweetman', 'Pringell', '2018-09-09', 3, 'ANALISTA', 1784);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (264, 'Maureen', 'Cleaton', 'Alibone', '2017-08-15', 7, 'VENTAS', 3314);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (265, 'Lucy', 'Franciottoi', 'Willmore', '2012-12-21', 10, 'VENTAS', 4466);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (266, 'Derrik', 'Darkin', 'Barbisch', '2016-03-16', 1, 'VENTAS', 3601);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (267, 'Corbett', 'Crust', 'McNellis', '2018-10-08', 10, 'ADMINISTRACIÓN', 1097);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (268, 'Ora', 'Bigley', 'Allum', '2007-05-26', 5, 'VENTAS', 1943);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (269, 'Damian', 'Vondrak', 'Juggins', '2005-01-20', 6, 'ANALISTA', 3816);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (270, 'Jere', 'Gatecliff', 'Simenel', '2003-04-25', 2, 'ANALISTA', 1464);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (271, 'Gabie', 'Tinklin', 'Fransseni', '2018-01-12', 9, 'ADMINISTRACIÓN', 2533);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (272, 'Adi', 'Middlebrook', 'Youle', '2006-03-27', 1, 'ADMINISTRACIÓN', 3599);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (273, 'Nalani', 'Sanja', 'Storey', '2011-08-26', 10, 'ANALISTA', 3876);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (274, 'Barthel', 'Sidwell', 'Abbiss', '2004-08-09', 7, 'ADMINISTRACIÓN', 1743);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (275, 'Linnell', 'Harriday', 'Kornalik', '2007-05-02', 1, 'VENTAS', 3040);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (276, 'Shayne', 'Macklin', 'Kenworthy', '2015-12-26', 8, 'VENTAS', 2153);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (277, 'Arabela', 'Garvie', 'Cornew', '2016-05-03', 1, 'VENTAS', 3799);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (278, 'Maible', 'Bridgewater', 'Peinton', '2008-10-26', 2, 'VENTAS', 3882);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (279, 'Juliane', 'Barracks', 'Shmyr', '2003-05-05', 10, 'ANALISTA', 2508);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (280, 'Myron', 'Lghan', 'Domenicone', '2004-08-20', 2, 'VENTAS', 2955);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (281, 'Arlette', 'Baldcock', 'Hagart', '2015-12-01', 9, 'ADMINISTRACIÓN', 2875);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (282, 'Spense', 'Houldcroft', 'Reinbech', '2003-04-21', 5, 'VENTAS', 3177);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (283, 'Neilla', 'Belf', 'Moorey', '2004-02-05', 1, 'VENTAS', 4678);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (284, 'Juieta', 'O'' Markey', 'Sliman', '2011-07-17', 1, 'VENTAS', 3235);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (285, 'Myrta', 'Jorn', 'Dunnett', '2012-06-06', 8, 'VENTAS', 4471);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (286, 'Jocelyne', 'Wickes', 'Covendon', '2014-06-27', 10, 'ANALISTA', 1714);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (287, 'Terese', 'Laviste', 'Romeuf', '2011-03-20', 2, 'VENTAS', 3035);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (288, 'Marlowe', 'Jouhning', 'Brosenius', '2004-04-15', 7, 'ADMINISTRACIÓN', 1667);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (289, 'Arman', 'Milsted', 'Sample', '2012-05-27', 2, 'ANALISTA', 2693);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (290, 'Terrell', 'MacBey', 'Schulze', '2003-07-22', 1, 'ADMINISTRACIÓN', 3763);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (291, 'Marlin', 'Blackadder', 'Lusher', '2007-11-07', 10, 'ANALISTA', 4030);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (292, 'Cari', 'Succamore', 'Rapport', '2003-12-08', 1, 'ADMINISTRACIÓN', 1190);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (293, 'Katy', 'Ripping', 'Holstein', '2009-10-12', 10, 'VENTAS', 1846);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (294, 'Lucy', 'Scrimgeour', 'Biskupek', '2014-03-06', 10, 'VENTAS', 1123);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (295, 'Inglis', 'Dymidowicz', 'Peppett', '2017-06-25', 1, 'ADMINISTRACIÓN', 2622);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (296, 'Mia', 'Arkcoll', 'Farfoot', '2016-11-15', 6, 'ADMINISTRACIÓN', 1630);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (297, 'Selena', 'Eve', 'Jeannon', '2008-06-05', 6, 'ADMINISTRACIÓN', 988);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (298, 'Nata', 'Corston', 'Peasey', '2017-01-27', 5, 'ADMINISTRACIÓN', 3075);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (299, 'Maxie', 'Endrighi', 'Algore', '2007-03-26', 10, 'VENTAS', 1076);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (300, 'Lyssa', 'Stapford', 'Duffer', '2010-08-02', 8, 'VENTAS', 4367);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (301, 'Fallon', 'Millan', 'Gunther', '2018-09-28', 10, 'ANALISTA', 4360);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (302, 'Britt', 'Nightingale', 'MacFadin', '2008-11-01', 8, 'VENTAS', 4557);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (303, 'Tricia', 'Issac', 'Oldis', '2004-05-15', 3, 'VENTAS', 1253);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (304, 'Tonie', 'Denney', 'Kerslake', '2005-04-29', 4, 'ANALISTA', 1321);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (305, 'Gilbertine', 'Deniske', 'Beese', '2012-09-20', 9, 'ADMINISTRACIÓN', 2907);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (306, 'Boycie', 'Norcock', 'Sabate', '2006-09-26', 7, 'ANALISTA', 1288);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (307, 'Jamil', 'Fuller', 'Denes', '2008-04-26', 2, 'ANALISTA', 3447);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (308, 'Shurlocke', 'Beese', 'Gleave', '2017-01-30', 3, 'ADMINISTRACIÓN', 1994);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (309, 'Horst', 'Perillio', 'Smieton', '2016-09-07', 1, 'ADMINISTRACIÓN', 3309);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (310, 'Krysta', 'Rizzelli', 'Payton', '2015-11-12', 7, 'ANALISTA', 3905);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (311, 'Jeth', 'Bellord', 'Swaine', '2008-04-24', 10, 'ADMINISTRACIÓN', 3739);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (312, 'Jaquith', 'Gathercoal', 'Atley', '2018-08-07', 6, 'ANALISTA', 2703);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (313, 'Coral', 'Steptoe', 'Isaacs', '2016-11-23', 2, 'ADMINISTRACIÓN', 1794);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (314, 'Vanni', 'Domingues', 'Shilstone', '2016-04-25', 5, 'ANALISTA', 1134);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (315, 'Mordecai', 'Walwood', 'Gregoli', '2007-09-04', 3, 'ADMINISTRACIÓN', 3310);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (316, 'Legra', 'Armstrong', 'Buxey', '2016-02-03', 1, 'ADMINISTRACIÓN', 1685);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (317, 'Ignacius', 'Matusov', 'Bristoe', '2007-12-30', 4, 'ANALISTA', 2097);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (318, 'Julie', 'Bleiman', 'Matusson', '2006-05-16', 7, 'ADMINISTRACIÓN', 996);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (319, 'Giovanna', 'Rabbatts', 'McKinie', '2017-04-08', 10, 'ADMINISTRACIÓN', 1185);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (320, 'Estele', 'Iveans', 'Archer', '2003-06-13', 5, 'ANALISTA', 1867);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (321, 'Domingo', 'Cure', 'Mendonca', '2014-06-03', 9, 'ANALISTA', 4200);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (322, 'Gianina', 'Bortoli', 'Zelley', '2018-03-23', 1, 'VENTAS', 3726);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (323, 'Rosemarie', 'Nowick', 'Walton', '2019-01-02', 1, 'ADMINISTRACIÓN', 2382);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (324, 'Ali', 'Ville', 'Spillett', '2017-11-22', 8, 'ADMINISTRACIÓN', 2043);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (325, 'Shell', 'Buist', 'Hainey', '2006-01-04', 5, 'VENTAS', 4469);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (326, 'Hulda', 'Stitt', 'Lindroos', '2015-05-30', 1, 'ADMINISTRACIÓN', 2548);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (327, 'Rosa', 'Willis', 'Hamprecht', '2016-02-01', 7, 'ADMINISTRACIÓN', 947);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (328, 'Lezlie', 'Jeafferson', 'Putterill', '2006-04-10', 3, 'ADMINISTRACIÓN', 1050);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (329, 'Colline', 'Angrove', 'Birchner', '2011-02-09', 8, 'ADMINISTRACIÓN', 912);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (330, 'Sherrie', 'Alps', 'Prichet', '2015-12-07', 9, 'ANALISTA', 4168);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (331, 'Nathan', 'Camelli', 'Dungate', '2018-07-23', 10, 'ADMINISTRACIÓN', 2518);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (332, 'Jan', 'Atterbury', 'Eddis', '2006-07-18', 5, 'VENTAS', 2157);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (333, 'Brendon', 'Bacop', 'Coleshill', '2013-03-13', 4, 'ADMINISTRACIÓN', 4091);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (334, 'Juliane', 'Ovill', 'Kilcullen', '2011-02-12', 1, 'VENTAS', 4477);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (335, 'Amalita', 'Ellington', 'Grigoletti', '2010-03-14', 5, 'ADMINISTRACIÓN', 3185);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (336, 'Simone', 'Lidgely', 'Alentyev', '2014-09-19', 8, 'ANALISTA', 4924);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (337, 'Winny', 'Teek', 'Rosle', '2017-09-29', 2, 'ADMINISTRACIÓN', 2287);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (338, 'Garrott', 'Salvadori', 'Petken', '2018-12-30', 4, 'ADMINISTRACIÓN', 2446);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (339, 'Ted', 'Gaylor', 'Woolfenden', '2010-03-07', 10, 'ANALISTA', 1716);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (340, 'Gustavo', 'Di Maria', 'Ivanisov', '2016-11-01', 10, 'VENTAS', 3702);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (341, 'Gideon', 'Alcott', 'Fairlaw', '2005-04-24', 9, 'ANALISTA', 2081);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (342, 'Sonni', 'Morphew', 'Woodnutt', '2003-08-23', 5, 'ADMINISTRACIÓN', 2741);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (343, 'George', 'Kilian', 'Bengal', '2018-03-23', 5, 'VENTAS', 1672);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (344, 'Justin', 'Bode', 'Amthor', '2003-07-12', 10, 'ADMINISTRACIÓN', 4971);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (345, 'Emalia', 'Coleson', 'Hailston', '2010-06-07', 4, 'ADMINISTRACIÓN', 4890);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (346, 'Dianemarie', 'Sangwin', 'Ludwikiewicz', '2008-06-08', 9, 'ANALISTA', 4232);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (347, 'Merilyn', 'Rodmell', 'Trevor', '2016-05-24', 10, 'VENTAS', 3660);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (348, 'Gordon', 'Warrell', 'Corradino', '2008-08-06', 5, 'ANALISTA', 4697);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (349, 'Dacia', 'Pinchback', 'Brokenshaw', '2008-01-17', 1, 'ANALISTA', 4539);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (350, 'Palmer', 'Frankowski', 'McGow', '2010-01-16', 5, 'VENTAS', 3766);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (351, 'Nikos', 'Crofts', 'Tremblet', '2017-09-07', 8, 'ANALISTA', 4592);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (352, 'Corey', 'Wiles', 'Philippard', '2004-07-30', 10, 'ANALISTA', 3874);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (353, 'Tomaso', 'Ference', 'Trill', '2012-01-28', 8, 'ADMINISTRACIÓN', 1570);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (354, 'Milicent', 'Disney', 'Norquoy', '2007-08-18', 10, 'VENTAS', 4215);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (355, 'Electra', 'Takle', 'Banger', '2010-02-24', 1, 'ANALISTA', 1119);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (356, 'Glen', 'Renowden', 'Awde', '2005-05-06', 6, 'ANALISTA', 4091);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (357, 'Miriam', 'Britto', 'MacPike', '2004-11-10', 7, 'ANALISTA', 1562);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (358, 'Eddy', 'Rushworth', 'Milthorpe', '2003-11-15', 1, 'ADMINISTRACIÓN', 1084);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (359, 'Kiley', 'Larmet', 'Guiton', '2012-11-16', 4, 'VENTAS', 1667);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (360, 'Matteo', 'Briar', 'Klosterman', '2012-08-13', 7, 'ANALISTA', 1873);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (361, 'Tammie', 'Cluff', 'Baversor', '2011-11-14', 2, 'ANALISTA', 4058);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (362, 'Griffin', 'Matusevich', 'Ricold', '2004-11-17', 6, 'ADMINISTRACIÓN', 1716);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (363, 'Izabel', 'Sacco', 'Booth', '2012-01-30', 7, 'ANALISTA', 2396);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (364, 'Webster', 'Ambrogelli', 'Cardiff', '2013-11-12', 2, 'VENTAS', 4332);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (365, 'Seth', 'Ipsley', 'Rayner', '2017-11-15', 8, 'ADMINISTRACIÓN', 2560);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (366, 'Chris', 'Markos', 'Candish', '2009-08-27', 1, 'ANALISTA', 1377);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (367, 'Shirley', 'Barcke', 'Catmull', '2004-07-22', 5, 'ANALISTA', 1917);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (368, 'Arabelle', 'State', 'Bubeer', '2019-05-18', 8, 'ADMINISTRACIÓN', 907);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (369, 'Witty', 'Kennerknecht', 'Stitt', '2006-01-13', 8, 'ANALISTA', 2873);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (370, 'Darryl', 'Andras', 'Toghill', '2006-05-24', 9, 'ANALISTA', 1462);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (371, 'Joachim', 'Paramor', 'Burkhill', '2007-03-08', 7, 'VENTAS', 3029);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (372, 'Denice', 'Knoble', 'Boyan', '2007-08-24', 3, 'ANALISTA', 4962);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (373, 'Kaitlynn', 'Geeson', 'Santos', '2008-07-13', 6, 'ADMINISTRACIÓN', 2418);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (374, 'Adena', 'Petre', 'Woodsford', '2011-12-27', 3, 'ANALISTA', 2456);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (375, 'Tiff', 'McHarry', 'Joscelyn', '2009-01-20', 7, 'ADMINISTRACIÓN', 1770);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (376, 'Rhianna', 'Wildish', 'McCome', '2016-05-13', 3, 'VENTAS', 1947);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (377, 'Madlin', 'Symper', 'Southerell', '2012-08-19', 6, 'ANALISTA', 3518);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (378, 'Lloyd', 'Matejic', 'Hackly', '2017-05-21', 2, 'ANALISTA', 2487);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (379, 'Jozef', 'Corgenvin', 'Tuley', '2013-01-18', 7, 'ANALISTA', 1699);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (380, 'Valene', 'Domenichini', 'Fenby', '2019-02-15', 7, 'ANALISTA', 3423);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (381, 'Sanderson', 'Gaitley', 'Cridland', '2009-06-23', 2, 'ANALISTA', 3195);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (382, 'Katerine', 'McEntee', 'Emlyn', '2016-03-14', 8, 'VENTAS', 2553);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (383, 'Kirstyn', 'Braffington', 'McTerry', '2017-05-06', 4, 'ADMINISTRACIÓN', 4178);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (384, 'Leelah', 'Heathwood', 'Ryding', '2013-01-04', 5, 'ADMINISTRACIÓN', 1540);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (385, 'Avigdor', 'Boam', 'Ballin', '2013-07-29', 2, 'VENTAS', 3860);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (386, 'Abigael', 'Briztman', 'Gwillim', '2019-07-02', 10, 'ADMINISTRACIÓN', 1352);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (387, 'Lulita', 'Arrow', 'Baxter', '2014-04-20', 7, 'VENTAS', 4754);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (388, 'Jenn', 'Javes', 'Dibling', '2008-04-24', 4, 'VENTAS', 3348);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (389, 'Chance', 'Summerscales', 'McRoberts', '2015-08-10', 2, 'VENTAS', 3480);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (390, 'Brendin', 'Jimmes', 'Crosbie', '2004-12-13', 5, 'ADMINISTRACIÓN', 2764);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (391, 'Stavros', 'McKew', 'Richings', '2012-05-25', 8, 'VENTAS', 1080);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (392, 'Thomasina', 'Laudham', 'Edgehill', '2017-01-04', 10, 'VENTAS', 4508);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (393, 'Ronny', 'Adamowitz', 'Prosch', '2019-05-16', 7, 'VENTAS', 3617);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (394, 'Ericha', 'Garrie', 'Glaze', '2006-05-21', 10, 'ANALISTA', 4268);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (395, 'Anders', 'Burkhill', 'Kleinhausen', '2012-05-21', 6, 'VENTAS', 3969);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (396, 'Shermy', 'McGairl', 'Scothorne', '2017-12-27', 8, 'ADMINISTRACIÓN', 4247);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (397, 'Marika', 'Joberne', 'Scholte', '2003-06-21', 2, 'ANALISTA', 3757);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (398, 'Broderic', 'Erington', 'Tomashov', '2018-04-05', 5, 'ANALISTA', 2227);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (399, 'Verina', 'McVitie', 'Morrallee', '2008-08-27', 10, 'ANALISTA', 2552);
insert into empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) values (400, 'Zebadiah', 'Sirmon', 'Khidr', '2005-03-08', 7, 'VENTAS', 2640);

--Nos añadimos a nosotros
INSERT INTO empleados (cod_emp, nombre, apellido1, apellido2, contratado, departamento, trabajo, salario) VALUES (401, 'Juan Manuel', 'Mena', 'Hernandez', '2003-01-01', 7, 'DIRECCION', 5000);

--Seleccionamos responsables
SELECT cod_emp, nombre, apellido1 FROM empleados ORDER BY rand() LIMIT 4;

--Cambiamos los empleados a responsables
UPDATE empleados SET trabajo='RESPONSABLE' WHERE cod_emp = 4;

--Cambiamos los salarios de los distintos puestos

UPDATE empleados SET salario=2850 WHERE trabajo='RESPONSABLE';

