/*
Pedir un número, menor que 10 y sacar y mostrar tantos números aleatorios,
de uno en uno, como se haya indicado
*/

SELECT DBMS_RANDOM.VALUE FROM DUAL;

SELECT SUBSTR(DBMS_RANDOM.VALUE,5,1) FROM DUAL;

-- SACAR 4 NÚMEROS ALEATORIOS
DECLARE
    CONTADOR INTEGER;
    ALEATORIO VARCHAR2(2):='';
    RESULTADO VARCHAR2(10):='';

BEGIN
    CONTADOR:=&CONTADOR;
    WHILE CONTADOR>0 LOOP
        ALEATORIO:=SUBSTR(DBMS_RANDOM.VALUE,5,1);
        CONTADOR:=CONTADOR - 1;
        RESULTADO:=CONCAT(RESULTADO,ALEATORIO);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('NÚMERO ALEATORIO: '||RESULTADO);
END;