-- Crear usuario en Oracle

CREATE USER coordenadas IDENTIFIED BY secreto
default tablespace users;
grant connect,create session, resource to trofeo_alcaldesa;
grant resource to trofeo_alcaldesa;

-- Crear tabla tarjetas

  CREATE TABLE "COORDENADAS"."TARJETAS" 
   (	"USUARIO" NUMBER(10,0) NOT NULL ENABLE, 
	"LETRA" CHAR(1 BYTE) NOT NULL ENABLE, 
	"NUMERO" NUMBER(1,0) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TARJETAS_PK" PRIMARY KEY ("USUARIO", "LETRA", "NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "TARJETAS_VALOR_CHK1" CHECK (REGEXP_LIKE(VALOR,'/d{3}')) ENABLE, 
	 CONSTRAINT "TARJETAS_LET_CHK1" CHECK (LETRA=UPPER('A') OR LETRA=UPPER('B') OR LETRA=UPPER('C')) ENABLE, 
	 CONSTRAINT "TARJETAS_NUM_CHK1" CHECK (NUMERO > 0 AND NUMERO < 6) ENABLE, 
	 CONSTRAINT "TARJETAS_USU_CHK1" CHECK (USUARIO > 0) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

 -- Inserts en tabla

INSERT INTO TARJETAS VALUES(1,'A','1','453');
INSERT INTO TARJETAS VALUES(1,'A','2','321');
INSERT INTO TARJETAS VALUES(1,'A','3','222');
INSERT INTO TARJETAS VALUES(1,'A','4','124');
INSERT INTO TARJETAS VALUES(1,'A','5','098');

INSERT INTO TARJETAS VALUES(1,'B','1','560');
INSERT INTO TARJETAS VALUES(1,'B','2','120');
INSERT INTO TARJETAS VALUES(1,'B','3','090');
INSERT INTO TARJETAS VALUES(1,'B','4','333');
INSERT INTO TARJETAS VALUES(1,'B','5','163');

INSERT INTO TARJETAS VALUES(1,'C','1','195');
INSERT INTO TARJETAS VALUES(1,'C','2','369');
INSERT INTO TARJETAS VALUES(1,'C','3','001');
INSERT INTO TARJETAS VALUES(1,'C','4','987');
INSERT INTO TARJETAS VALUES(1,'C','5','951');

INSERT INTO TARJETAS VALUES(2,'A','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'A','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'A','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'A','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'A','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(2,'B','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'B','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'B','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'B','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'B','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(2,'C','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'C','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'C','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'C','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(2,'C','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(3,'A','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'A','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'A','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'A','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'A','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(3,'B','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'B','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'B','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'B','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'B','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(3,'C','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'C','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'C','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'C','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(3,'C','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(4,'A','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'A','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'A','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'A','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'A','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(4,'B','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'B','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'B','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'B','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'B','5',floor(dbms_random.value*1000));

INSERT INTO TARJETAS VALUES(4,'C','1',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'C','2',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'C','3',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'C','4',floor(dbms_random.value*1000));
INSERT INTO TARJETAS VALUES(4,'C','5',floor(dbms_random.value*1000));

-- Comprobamos valor

SELECT VALOR FROM tarjetas WHERE LETRA='B' AND NUMERO='2';

-- Bloque de codigo que muestra las coordenadas del usuario 1 en formato matriz.

DECLARE
    V_USUARIO TARJETAS.USUARIO%TYPE;
    V_VALORA   TARJETAS.VALOR%TYPE;
    V_VALORB   TARJETAS.VALOR%TYPE;
    V_VALORC   TARJETAS.VALOR%TYPE;
    V_NUMERO  TARJETAS.NUMERO%TYPE;
BEGIN
	dbms_output.put_line('A 	B 	C');	
    V_USUARIO:=1;
	FOR V_NUMERO IN 1..5
	LOOP
		SELECT TARJETAS.VALOR INTO V_VALORA
    	FROM TARJETAS WHERE TARJETAS.USUARIO=V_USUARIO AND TARJETAS.LETRA='A' AND TARJETAS.NUMERO=V_NUMERO;

    	SELECT TARJETAS.VALOR INTO V_VALORB
    	FROM TARJETAS WHERE TARJETAS.USUARIO=V_USUARIO AND TARJETAS.LETRA='B' AND TARJETAS.NUMERO=V_NUMERO;

    	SELECT TARJETAS.VALOR INTO V_VALORC
    	FROM TARJETAS WHERE TARJETAS.USUARIO=V_USUARIO AND TARJETAS.LETRA='C' AND TARJETAS.NUMERO=V_NUMERO;

    	dbms_output.put_line(V_VALORA || '	' || V_VALORB || '	' || V_VALORC || '<<' || V_NUMERO || '>>');
	END LOOP;

END;

-- Bloque de codigo que muestra las coordenadas del un usuario en formato matriz.

DECLARE
    V_USUARIO TARJETAS.USUARIO%TYPE;
    V_VALORA    TARJETAS.VALOR%TYPE;
    V_VALORB    TARJETAS.VALOR%TYPE;
    V_VALORC    TARJETAS.VALOR%TYPE;
    V_NUMERO   TARJETAS.NUMERO%TYPE;
BEGIN
	dbms_output.put_line('A 	B 	C');	
    V_USUARIO:='&USUARIO';
	FOR V_NUMERO IN 1..5
	LOOP
		SELECT TARJETAS.VALOR INTO V_VALORA
    	FROM TARJETAS WHERE TARJETAS.USUARIO=V_USUARIO AND TARJETAS.LETRA='A' AND TARJETAS.NUMERO=V_NUMERO;

    	SELECT TARJETAS.VALOR INTO V_VALORB
    	FROM TARJETAS WHERE TARJETAS.USUARIO=V_USUARIO AND TARJETAS.LETRA='B' AND TARJETAS.NUMERO=V_NUMERO;

    	SELECT TARJETAS.VALOR INTO V_VALORC
    	FROM TARJETAS WHERE TARJETAS.USUARIO=V_USUARIO AND TARJETAS.LETRA='C' AND TARJETAS.NUMERO=V_NUMERO;

    	dbms_output.put_line(V_VALORA || '	' || V_VALORB || '	' || V_VALORC || '<<' || V_NUMERO || '>>');
	END LOOP;

END;
