--------------------------------------------------------
-- Archivo creado  - martes-marzo-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "FARMACIA"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FARMACIA.CATEGORIA
SET DEFINE OFF;
Insert into FARMACIA.CATEGORIA (ID_CATEGORIA,NOMBRE) values ('1','APÓSITO');
Insert into FARMACIA.CATEGORIA (ID_CATEGORIA,NOMBRE) values ('2','CREMA');
Insert into FARMACIA.CATEGORIA (ID_CATEGORIA,NOMBRE) values ('3','GEL');
Insert into FARMACIA.CATEGORIA (ID_CATEGORIA,NOMBRE) values ('4','COMPRIMIDO');
Insert into FARMACIA.CATEGORIA (ID_CATEGORIA,NOMBRE) values ('5','COMPRIMIDO EFERVESCENTE');
--------------------------------------------------------
--  DDL for Index CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARMACIA"."CATEGORIA_PK" ON "FARMACIA"."CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "FARMACIA"."CATEGORIA" ADD CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FARMACIA"."CATEGORIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "FARMACIA"."CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "FARMACIA"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(11,0), 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"FABRICANTE" VARCHAR2(250 BYTE), 
	"PRECIO_COMPRA" NUMBER(6,2), 
	"PRECIO_VENTA" NUMBER(11,0), 
	"ID_CATEGORIA" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into FARMACIA.PRODUCTO
SET DEFINE OFF;
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('1','IBUPROFENO','NORMON','1,25','1','4');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('2','PARACETAMOL','AUROVITAS','1,05','1','4');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('3','ASPIRINA','BAYER','2,25','2','4');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('4','SILVEDERMA','ALDO-UNION','4,75','5','2');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('5','CAPSIDOL','LABORATORIO VIÑAS','1,25','1','2');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('6','ACICLOVIR','TEVA','4,65','5','2');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('7','ACETILSTEINA','CINFA','5,15','5','5');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('8','CALODIS','ESTEVE PHARMACEUTICAL, S. A.','1,25','1','4');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('9','DICLODOR','TEVA ESPAÑA','5,2','5','1');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('10','HANSATERM','BEIERSDORF ALEMANIA','3,25','3','1');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('11','TULGRASUM','LABORATORIO FARMACEUTICAL','12,56','13','1');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('12','NOVIDOL','MENARINI CONSUMER HEALTH','7,25','8','3');
Insert into FARMACIA.PRODUCTO (ID_PRODUCTO,NOMBRE,FABRICANTE,PRECIO_COMPRA,PRECIO_VENTA,ID_CATEGORIA) values ('13','ITNOGEN','KYOWA KIRIN HOLDINGS B. V.','6,2','6','1');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARMACIA"."TABLE1_PK" ON "FARMACIA"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "FARMACIA"."PRODUCTO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FARMACIA"."PRODUCTO" MODIFY ("FABRICANTE" NOT NULL ENABLE);
  ALTER TABLE "FARMACIA"."PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "FARMACIA"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "FARMACIA"."PRODUCTO" ADD CONSTRAINT "TABLE1_FK1" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "FARMACIA"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
